config/routes.rb
Epcot::Application.routes.draw do
  root :to => 'restaurants#index'
  devise_for :users
  
  resources :reports, :only => %w(index new create show)

  resources :users, :only => %w() do 
    resources :dishes, :controller => 'user_dishes', :only => %w(index)
  end

  resources :restaurants, :only => %w(index) do
    resources :dishes, :controller => 'restaurant_dishes', :only => %w(index show)
  end
  
  resources :dishes, :only => %w(index) do
    resources :reviews, :controller => 'dish_reviews', :only => %w(create update show index)
    resource :check, :only => %w(create destroy), :controller => 'dish_check'
  end
  
  resources :favorites, :only => %w(index)
  

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/restaurant_dishes_controller.rb
class RestaurantDishesController < ApplicationController
  respond_to :html, :js

  before_filter :set_restaurant

  # GET /restaurant/:restaurant_id/dishes
  def index
    @dishes = @restaurant.dishes.order(sort_order, :name).includes(:restaurant)
    respond_with(@dishes)
  end
  
  def show
    @dish = @restaurant.dishes.find_by_slug(params[:id])

    if user_signed_in?
      @review = @dish.reviews.find_by_user_id(current_user.id) || @dish.reviews.new(:rating => 5)
    end

    respond_with(@dish)
  end
  
  private
  
  def set_restaurant
    @restaurant = Restaurant.find_by_slug(params[:restaurant_id])
  end
  
  def sort_order
    params[:order] ||= 'category'
    order = params[:order].split("-").join(" ")
  end
end

app/views/restaurant_dishes/index.html.haml
- content_for(:header) do
  %h1{ :class => "left" }= @restaurant.name
  %div{"data-role" => "fieldcontain", "data-icon" => "gear", "class" => "ui-btn-right header-select"}
    = form_tag(restaurant_dishes_path(@restaurant), :method => :get, :class => "dish_order") do |f|
      = select_tag :order, options_for_select([['Sort by Category', 'category'], ["Sort by Dish", "name"], ["Sort by Popularity", "dish_checks_count-desc"], ["Sort by Rating", "rating"], ["Sort by Price", "price"]], :selected => params[:order])

%div{ "data-role" => "content"}
  %ul{ "data-role" => "listview", :class => "ui-listview ui-shadow" }
    = render @dishes

app/views/restaurant_dishes/show.html.haml
- content_for(:header) do
  = link_to @restaurant.name, restaurant_dishes_path(@restaurant), "class" => "ui-btn-left", "data-icon" => "arrow-l"
  %h1= @dish.name

%div{ "data-role" => "content"}
  %div{ "class" => "ui-body ui-body-d"}
    = render :partial => 'dishes/details', :locals => { :dish => @dish }

  %br
  %div{ "class" => "ui-body ui-body-d"}
    - if !user_signed_in?
      %p
        = link_to 'Sign In', new_user_session_path
        or
        = link_to 'Sign Up', new_user_registration_path
        to track what you've tried!
    - elsif @review
      %div{"data-role" => "collapsible", "data-theme" => "c"}
        %h3 Your Rating and Review for Dish
        %div
          = render :partial => "dish_reviews/form", :locals => { :dish => @dish, :review => @review }

    - if @dish.reviews.count > 0
      %h3 Reviews (#{@dish.reviews_count})

      %ul{ "data-role" => "listview", :class => "ui-listview ui-listview-inset ui-shadow", "data-inset" => true }
        - @dish.reviews.with_review.reverse_cronological.each do |review|
          %li{ "data-theme" => "c", "class" => "ui-li-has-arrow" }
            %div{"class" => "ui-btn-text"}
              = link_to dish_review_path(@dish, review), "class" => "ui-link-inherit" do
                %p{ "class" => "ui-li-aside ui-li-desc" }
                  %strong= review.created_at.to_s(:long)
                %h3 #{review.rating} - #{review.title}
                %p{ "class" => "ui-li-desc" }
                  %strong By #{review.user.username}
                %p{ "class" => "ui-li-desc" }= truncate(review.review, :length => 140)
              %span{ "class" => "ui-icon ui-icon-arrow-r ui-icon-shadow"}
    - else
      %p No ratings or reviews yet for this dish