config/routes.rb
Epcot::Application.routes.draw do
  root :to => 'restaurants#index'
  devise_for :users
  
  resources :reports, :only => %w(index new create show)

  resources :users, :only => %w() do 
    resources :dishes, :controller => 'user_dishes', :only => %w(index)
  end

  resources :restaurants, :only => %w(index) do
    resources :dishes, :controller => 'restaurant_dishes', :only => %w(index show)
  end
  
  resources :dishes, :only => %w(index) do
    resources :reviews, :controller => 'dish_reviews', :only => %w(create update show index)
    resource :check, :only => %w(create destroy), :controller => 'dish_check'
  end
  
  resources :favorites, :only => %w(index)
  

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/dish_reviews_controller.rb
class DishReviewsController < ApplicationController
  respond_to :html, :js
  before_filter :set_dish
  before_filter :set_restaurant

  # POST /dishes/:dish_id/reviews
  def create
    @review = @dish.reviews.new(params[:review].merge(:user_id => current_user.id))

    flash[:notice] = "Review successfully created" if @review.save
    respond_with(@review, :layout => !request.xhr?)
  end
  
  # POST /dishes/:dish_id/reviews
  def update
    @review = current_user.reviews.where(:reviewable_id => @dish.id, :reviewable_type => 'Dish').first!
    flash[:notice] = "Review updated created" if @review.update_attributes(params[:review])
    respond_with(@review, :layout => !request.xhr? )
  end
  
  # GET /dishes/:dish_id/reviews/:id
  def show
    @review = Review.find(params[:id])
  end
  
  private
  
  def set_dish
    @dish = Dish.find_by_slug(params[:dish_id])
  end
  def set_restaurant
    @restaurant = @dish.restaurant
  end
end

app/views/dish_reviews/_form.html.haml
= form_for(review, :url => review.new_record? ? dish_reviews_path(dish) : dish_review_path(dish, review), :remote => true, :html => { "data-ajax" => false }) do |f|
  %div{ "id" => "dish_review_#{dish.id}", :class => "error" }
  %div{ "data-role" => "fieldcontain" }
    = f.label :title
    = f.text_field :title
  %div{ "data-role" => "fieldcontain" }
    = f.label :review
    = f.text_area :review
  %div{ "data-role" => "fieldcontain" }
    = f.label :rating
    = f.text_field :rating, "type" => "number", "min" => "0", "max" => "10",  "data-type" => "range", "class" => "ui-slider-input"
  %div{ "data-role" => "fieldcontain" }
    = f.submit "Submit"

app/views/dish_reviews/create.js.erb
<% if @review.errors.any? %>
  // Create a list of errors
  var errors = $('<ul />');

  <% @review.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript( error ) %></li>');
  <% end %>

  // Display errors on form
  $('.errors').empty();
  $('#dish_review_<%= @review.reviewable.id %>').html(errors);

<% else %>
  $('.errors').empty();
  window.location = '<%= dish_review_path(@review.reviewable, @review) %>';
<% end %>

app/views/dish_reviews/show.html.haml
- content_for(:header) do
  = link_to @dish.short_name, restaurant_dish_path(@restaurant, @dish), "class" => "ui-btn-left", "data-icon" => "arrow-l"
  %h1= @review.title

%div{ "data-role" => "content"}

  %h2 Review of #{@dish.name}
  %div{ "class" => "ui-body ui-body-d"}
    = render :partial => 'dishes/details', :locals => { :dish => @dish }

  %br
  %div{ "class" => "ui-body ui-body-d"}
    - if @review.has_review?
      %h3= @review.title
      %p Reviewed by #{@review.user.username}
      %p= @review.review
    %p Rating: #{@review.rating}

app/views/dish_reviews/update.js.erb
<% if @review.errors.any? %>
  // Create a list of errors
  var errors = $('<ul />');

  <% @review.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript( error ) %></li>');
  <% end %>

  // Display errors on form
  $('.errors').empty();
  $('#dish_review_<%= @review.reviewable.id %>').html(errors);

<% else %>
  $('.errors').empty();
  window.location = '<%= dish_review_path(@review.reviewable, @review) %>';
<% end %>