config/routes.rb
Epcot::Application.routes.draw do
  root :to => 'restaurants#index'
  devise_for :users
  
  resources :reports, :only => %w(index new create show)

  resources :users, :only => %w() do 
    resources :dishes, :controller => 'user_dishes', :only => %w(index)
  end

  resources :restaurants, :only => %w(index) do
    resources :dishes, :controller => 'restaurant_dishes', :only => %w(index show)
  end
  
  resources :dishes, :only => %w(index) do
    resources :reviews, :controller => 'dish_reviews', :only => %w(create update show index)
    resource :check, :only => %w(create destroy), :controller => 'dish_check'
  end
  
  resources :favorites, :only => %w(index)
  

  match ':controller(/:action(/:id(.:format)))'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged
  has_many :dishes, :dependent => :destroy

  validates :name, :presence => true, length: { :maximum => 250 }
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.order(sort_order).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :ok }
    end
  end
  
  private
  def sort_order
    params[:order] ||= :booth_order
    params[:order]
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def icon_for_restaurant(restaurant)
    "restaurants/#{restaurant.slug}.png"
  end

  def restaurant_sort_link(current_order)
    other_order = (current_order == 'name') ? :booth_order : :name
    order = other_order.to_s.split("_").join(" ")
    link_to "sort by #{order}", restaurants_path(:order => other_order), "data-icon" => "gear",  "class" => "ui-btn-right"
  end
end

app/views/restaurants/_form.html.haml
= form_for @restaurant do |f|
  -if @restaurant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@restaurant.errors.count, "error")} prohibited this restaurant from being saved:"
      %ul
        - @restaurant.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :country_id
    = f.number_field :country_id
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/restaurants/edit.html.haml
%h1 Editing restaurant

= render 'form'

= link_to 'Show', @restaurant
\|
= link_to 'Back', restaurants_path

app/views/restaurants/index.html.haml
- content_for(:header) do
  %h1{ :class => "left" } Epcot Food & Wine
  = restaurant_sort_link(params[:order])

%div{ "data-role" => "content"}
  %ul{ "data-role" => "listview", :class => "ui-listview ui-corner-all ui-shadow" }
    - @restaurants.each do |restaurant|
      %li{ "class" => "ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-count ui-li-has-icon"}

        %div{ "class" => "ui-btn-text" }
        = link_to restaurant_dishes_path(restaurant), "class" => "ui-link-inherit" do
          = image_tag icon_for_restaurant(restaurant), :alt => restaurant.name, :class => "ui-li-icon ui-li-thumb ui-icon-flag"
          = restaurant.name
          %span{"class" => "ui-li-count ui-btn-up-c ui-btn-corner-all"}= pluralize(restaurant.dishes_count, "dish")
          %span{"class" => "ui-icon ui-icon-arrow-r ui-icon-shadow"}

app/views/restaurants/new.html.haml
%h1 New restaurant

= render 'form'

= link_to 'Back', restaurants_path

app/views/restaurants/show.html.haml
%p#notice= notice

%p
  %b Slug:
  = @restaurant.slug
%p
  %b Country:
  = @restaurant.country_id
%p
  %b Category:
  = @restaurant.category
%p
  %b Name:
  = @restaurant.name

= link_to 'Edit', edit_restaurant_path(@restaurant)
\|
= link_to 'Back', restaurants_path