config/routes.rb
Epcot::Application.routes.draw do
  root :to => 'restaurants#index'
  devise_for :users
  
  resources :reports, :only => %w(index new create show)

  resources :users, :only => %w() do 
    resources :dishes, :controller => 'user_dishes', :only => %w(index)
  end

  resources :restaurants, :only => %w(index) do
    resources :dishes, :controller => 'restaurant_dishes', :only => %w(index show)
  end
  
  resources :dishes, :only => %w(index) do
    resources :reviews, :controller => 'dish_reviews', :only => %w(create update show index)
    resource :check, :only => %w(create destroy), :controller => 'dish_check'
  end
  
  resources :favorites, :only => %w(index)
  

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :ok }
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
= form_for @review do |f|
  -if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :reviewable_id
    = f.number_field :reviewable_id
  .field
    = f.label :reviewable_type
    = f.text_field :reviewable_type
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :rating
    = f.number_field :rating
  .field
    = f.label :review
    = f.text_area :review
  .actions
    = f.submit 'Save'

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h1 Listing reviews

%table
  %tr
    %th Reviewable
    %th Reviewable type
    %th User
    %th Rating
    %th Review
    %th
    %th
    %th

  - @reviews.each do |review|
    %tr
      %td= review.reviewable_id
      %td= review.reviewable_type
      %td= review.user_id
      %td= review.rating
      %td= review.review
      %td= link_to 'Show', review
      %td= link_to 'Edit', edit_review_path(review)
      %td= link_to 'Destroy', review, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Review', new_review_path

app/views/reviews/new.html.haml
%h1 New review

= render 'form'

= link_to 'Back', reviews_path

app/views/reviews/show.html.haml
%p#notice= notice

%p
  %b Reviewable:
  = @review.reviewable_id
%p
  %b Reviewable type:
  = @review.reviewable_type
%p
  %b User:
  = @review.user_id
%p
  %b Rating:
  = @review.rating
%p
  %b Review:
  = @review.review

= link_to 'Edit', edit_review_path(@review)
\|
= link_to 'Back', reviews_path